# Configure App Role and Components below

components:
  MySQL: true
  Redis: true
  RabbitMQ: true
  node:
    Role: master


# node:
# Role: slave
# MasterHost: 127.0.0.1:8080
# if you do not want to use RabbitMQ : set it false